<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text35_text35</name>
   <tag></tag>
   <elementGuidId>236ec442-5a19-47e6-9f71-aab831751078</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text35</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text35']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7f0af74d-7cb0-40ab-a965-f79012b6aa32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bfb822bb-eb2d-487e-a4cd-ea736ff9081c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text35</value>
      <webElementGuid>56e2ac63-826e-46ab-b080-8cbf768e7137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text35&quot;)</value>
      <webElementGuid>a2475dd9-957d-4f2b-ae1c-ed09391f0053</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text35']</value>
      <webElementGuid>c2f91432-ac64-42b4-bf15-3addcae4ec9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[35]</value>
      <webElementGuid>e4ae7835-febf-48e4-b7b0-93f6f5a6e147</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text35']</value>
      <webElementGuid>b5fba307-2b4d-4851-acc0-e6d869db5070</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
