<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text26_text26</name>
   <tag></tag>
   <elementGuidId>f429d918-b6e0-4115-909b-e755d0aacac1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text26</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text26']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0bbf0f06-daa6-44d8-8299-a7803566be7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>08bce18d-4ec4-42ad-bff6-e2b3e82f50b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text26</value>
      <webElementGuid>18b0b1b5-b1c1-4bd7-88cf-54de4b9c8e4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text26&quot;)</value>
      <webElementGuid>a1c54ca3-0eaf-43f1-88d1-bec1539ac789</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text26']</value>
      <webElementGuid>4cfca737-0698-4758-8100-c068bf6b7253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[26]</value>
      <webElementGuid>6bb3f2a9-47f1-41da-95f3-08d351555278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text26']</value>
      <webElementGuid>c0ebcd35-e40b-4fd6-898d-2cc0d53cf4ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
