<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text38_text38</name>
   <tag></tag>
   <elementGuidId>fdd9fffd-8aa7-4ac2-8588-aa943794c631</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text38</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text38']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a10ab826-bf6f-4c9f-9eba-2e9785804901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c9273e35-bfac-4f86-8ef2-32eb10e14be5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text38</value>
      <webElementGuid>24d9e3fc-5185-47d6-b2c9-a5f9034e5789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text38&quot;)</value>
      <webElementGuid>4418fe52-3a14-42bf-848d-80427061371f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text38']</value>
      <webElementGuid>24a71162-7fd2-4a27-9c0e-50f19e5ae65d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[38]</value>
      <webElementGuid>9ffaba64-921a-4128-b574-674adcf2b538</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text38']</value>
      <webElementGuid>cd2d8568-863f-47de-b06f-9b399cde7fff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
