<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text27_text27</name>
   <tag></tag>
   <elementGuidId>22113a14-7fc4-4336-867e-3e4955e3f5f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text27</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text27']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d345e407-6e91-4e91-ac29-0e166454ff12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b709765f-8e2f-4128-8d55-ce165169e5f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text27</value>
      <webElementGuid>6af90219-7b66-49d2-aa7b-80303f9e2bb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text27&quot;)</value>
      <webElementGuid>17d80b8e-ba36-4fff-8056-d7c50f276906</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text27']</value>
      <webElementGuid>338d5fa6-1bca-4782-9180-59d949d16d9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[27]</value>
      <webElementGuid>0615cfdf-f422-4c12-ba5a-4eddbf446c54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text27']</value>
      <webElementGuid>88de09ba-111e-4a0f-b459-a91503ee3762</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
