<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text10_text10</name>
   <tag></tag>
   <elementGuidId>b9e6357e-603b-4f41-8cce-848951398850</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text10</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text10']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a6c5877d-fc7b-4b0c-95bf-a7b061f9ae76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>748f4c52-c361-4256-b790-7e91df030278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text10</value>
      <webElementGuid>89cb8567-8ea3-4b3c-a172-5b96f0b91992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text10&quot;)</value>
      <webElementGuid>d01656ce-b0a8-4f39-8004-5bc310eb5006</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text10']</value>
      <webElementGuid>2300d1d5-5cde-4bce-b63d-9549ae84f305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[10]</value>
      <webElementGuid>9e9efe49-0999-4a8a-bd8b-dc38605c57c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text10']</value>
      <webElementGuid>04616eff-8744-42a6-8b08-32b35d92e3a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
