<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text39_text39</name>
   <tag></tag>
   <elementGuidId>27290c92-d58e-4f3e-8240-ed82e007f57c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text39</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text39']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cbc1230e-ee1a-41d1-8655-bd98e78ffb24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3945faa1-b6c1-4caf-8ba2-953e28f0cdb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text39</value>
      <webElementGuid>e201b5b2-7331-4958-97f6-fba217c632a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text39&quot;)</value>
      <webElementGuid>de25056f-c31b-4ec1-89d0-e1ba26e41550</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text39']</value>
      <webElementGuid>0958d580-c576-4727-974f-6550e2974313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[39]</value>
      <webElementGuid>f03a6599-0918-4aa5-b2e1-b6f94c2fc4e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text39']</value>
      <webElementGuid>59b1705b-d47e-457c-bc7f-95329588ba9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
