<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text32_text32</name>
   <tag></tag>
   <elementGuidId>47e749d7-5636-4216-9c23-361468b7cf5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text32</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text32']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1e8e252b-dae4-4784-91a5-d07c310b29b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>33c30715-ae4a-431e-9aad-5c203a74955a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text32</value>
      <webElementGuid>bf760c1d-b914-46f5-abee-89adfe9cf2bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text32&quot;)</value>
      <webElementGuid>53aee907-ffba-4b31-b279-58e624b4e220</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text32']</value>
      <webElementGuid>edc13b6d-098e-4599-95ee-75df4ef2b65e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[32]</value>
      <webElementGuid>c38f7551-fd95-4cda-9353-3777a821a71a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text32']</value>
      <webElementGuid>cd760232-5735-4507-b8b5-07aebeccb947</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
