<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text14_text14</name>
   <tag></tag>
   <elementGuidId>54bc2831-0d37-4de8-82f1-2fbb7bdc3893</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text14</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text14']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7af62d19-c016-4e49-8e15-fee80de4905b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1e54f879-833a-4c24-becd-bb5ebec93a9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text14</value>
      <webElementGuid>adc897ab-3efc-4d9a-8f16-9b93e1cfb9b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text14&quot;)</value>
      <webElementGuid>3d045196-7fc5-4847-ad80-bb4da7f15c53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text14']</value>
      <webElementGuid>1ae03651-d4e5-4c4c-b210-95f2567f0cbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[14]</value>
      <webElementGuid>9c803c89-f6a7-49ab-8e6e-dc009c34437b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text14']</value>
      <webElementGuid>848bd25f-52c0-40c9-a218-0145999f6082</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
