<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text24_text24</name>
   <tag></tag>
   <elementGuidId>a53e3a6d-f6c1-4361-a98f-036ba895145d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text24</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text24']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cd219cb5-1249-4a1c-bd94-d8718ad27d2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b4b7145e-47d7-4fd8-b530-6c40f51987a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text24</value>
      <webElementGuid>f9ef19c6-cdef-468a-9530-5ba707a50ee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text24&quot;)</value>
      <webElementGuid>0c060d64-0cdd-4fd7-a3ac-3696955b7d90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text24']</value>
      <webElementGuid>2ff9f04f-e16b-4748-9692-f5578d435463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[24]</value>
      <webElementGuid>d3dcba55-69fa-4109-9aad-1478e536cba3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text24']</value>
      <webElementGuid>70c425a3-4588-47e2-9340-d159d0ba7d92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
