<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text40_text40</name>
   <tag></tag>
   <elementGuidId>52788ce8-0112-4fe3-b351-e2768e1fd78e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text40</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text40']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c8b691c6-da09-44dd-8e5b-66981e6e2e27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4f39bb20-eb93-4af4-af8d-f38fa8ab81c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text40</value>
      <webElementGuid>86339c58-ccd3-4ecd-b621-993f7cce0968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text40&quot;)</value>
      <webElementGuid>805091ca-3584-4088-ac7b-9d0e91c38a54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text40']</value>
      <webElementGuid>8e4001df-f952-41bd-bd1c-fbff73bb79ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[40]</value>
      <webElementGuid>c9c386ed-7723-4999-a806-316571147089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text40']</value>
      <webElementGuid>c938b5b6-0ab1-4dfb-a965-3758571e7dc3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
