<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text20_text20</name>
   <tag></tag>
   <elementGuidId>300ab7a1-38f5-41eb-82ac-a13a20f73cc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text20</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text20']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d610c3ba-c7cc-47e0-a5e4-fe6056e31397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f128d2c5-54d0-46d8-be00-6bf41db3f9bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text20</value>
      <webElementGuid>bab1e3ec-ebc3-4ca9-a7a6-3d45d7ad0ade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text20&quot;)</value>
      <webElementGuid>255af6eb-92d0-4a84-9a3f-c375258081eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text20']</value>
      <webElementGuid>9236cb3f-b67e-45f7-bf39-f536f0f3a8dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[20]</value>
      <webElementGuid>0bf2a6da-9c04-46cd-bc51-004815f5c374</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text20']</value>
      <webElementGuid>c7228320-e20f-41f7-82a8-e13ca406cb1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
