<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text31_text31</name>
   <tag></tag>
   <elementGuidId>67b44dd4-d212-4147-9396-c44c055a1cd7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text31</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text31']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>08aa0944-f69a-4350-badb-beea6ee9c85a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2ff799f6-d93b-49ea-a5a5-52af4037b5c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text31</value>
      <webElementGuid>ac77cf54-28c5-4327-b9ad-f01214197a93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text31&quot;)</value>
      <webElementGuid>824dd6d5-b1ea-4262-b3b4-68b6c7dde73c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text31']</value>
      <webElementGuid>ed5b93ec-096f-4882-b259-d9084997aeb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[31]</value>
      <webElementGuid>687e75c6-e50d-4ea3-8ff1-7b04bfe98a25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text31']</value>
      <webElementGuid>d1a1a3d0-6f8a-420c-bbc7-a6a5355f0ce3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
