<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text23_text23</name>
   <tag></tag>
   <elementGuidId>d098c1e0-3586-4b16-89b9-9c3d60cd51b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text23</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text23']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>37c5447d-6141-467a-b143-f61524dad5ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cd5e5f08-34b7-4fa6-beda-8715beecf216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text23</value>
      <webElementGuid>1012225c-9618-4f11-ba3f-8b52dcdf7dff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text23&quot;)</value>
      <webElementGuid>f806d0ae-2bc3-415b-8c56-3f70a4d3c893</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text23']</value>
      <webElementGuid>2bf77e1e-d8ac-4d73-b558-f46d415753ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[23]</value>
      <webElementGuid>a490d697-524c-491d-90b1-5cff081020e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text23']</value>
      <webElementGuid>20205a7e-3923-4743-88b7-e37a63242a02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
