<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Radio2_radio3</name>
   <tag></tag>
   <elementGuidId>fbc943a9-fbf4-4124-af4f-f19272072084</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#radio3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>943c1b99-0d81-4539-afd6-cb93612862ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>b3746905-8ed2-4365-b37a-77abb7461550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio3</value>
      <webElementGuid>1ea0c143-0c65-475b-a43a-0b0012646b65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Radio3</value>
      <webElementGuid>f4fe3aa6-7a2d-4177-99ea-671943af017b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio3&quot;)</value>
      <webElementGuid>33c25b92-22bd-4f74-8c58-3c40d11ce303</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio3']</value>
      <webElementGuid>51e97ae8-3437-4320-a55b-94b93a71b8db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[23]</value>
      <webElementGuid>ecf33b69-329a-4bec-9914-d2d8029265b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'radio3']</value>
      <webElementGuid>c31130cf-164f-4846-9058-4bd3a05321f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
