<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Radio7_radio8</name>
   <tag></tag>
   <elementGuidId>4d4aad27-102b-48e9-b0e4-955cebbc5077</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#radio8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio8']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f46fbc7f-5381-4823-861a-02658e9912fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>2bc88eef-1a97-4e22-96b1-3db28f8a76bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio8</value>
      <webElementGuid>b7c58982-b205-4f88-8d1b-0f386a8828f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Radio8</value>
      <webElementGuid>84748967-ef4d-48e5-9b7d-0f61da0b1f0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio8&quot;)</value>
      <webElementGuid>22d6d4bf-47d9-4ec1-a796-97300f45b8e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio8']</value>
      <webElementGuid>afd76d84-1e85-4628-b0ac-5b70c5d2ad2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[28]</value>
      <webElementGuid>d6ee0387-0e83-40a9-8471-df4a55f05308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'radio8']</value>
      <webElementGuid>6e2ea18f-2628-42d9-8689-61083dc21142</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
