<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Radio3_radio4</name>
   <tag></tag>
   <elementGuidId>107a2fdc-7ff6-4ae9-b1bb-74913bab4d83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#radio4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c506ab86-9981-440c-9998-44f656d27631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>1647462f-b4d5-479a-9b41-d2de641b02de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio4</value>
      <webElementGuid>aa3cd4ad-b772-47d1-9634-e7920f27e993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Radio4</value>
      <webElementGuid>3c05ef9e-d977-40ad-84bb-81212e34e77b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio4&quot;)</value>
      <webElementGuid>76b791ab-c8d2-4a7f-83a4-3f4e30b8768b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio4']</value>
      <webElementGuid>d40ba7ac-12bc-4d46-a6a6-44674f161a30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[24]</value>
      <webElementGuid>79a4536c-ffe8-45f2-8387-a85bfe410fbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'radio4']</value>
      <webElementGuid>43181d9b-0d88-44f6-bcb1-da988757cc3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
