<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Checkbox7_checkbox8</name>
   <tag></tag>
   <elementGuidId>ee526f28-66a3-42c2-8d8e-3d0de26c5875</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkbox8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkbox8']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e9bcbd87-180a-48bc-b409-6ec3fbf5de9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>de7e7988-cc51-40ef-92f3-0e8e7001824f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox8</value>
      <webElementGuid>6fbacec3-198a-47b9-b23b-eea896784848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Checkbox8</value>
      <webElementGuid>198080ec-f472-43ef-a16d-afd5a18aa69a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox8&quot;)</value>
      <webElementGuid>db67be53-261d-454b-8057-e18dd1d67b4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkbox8']</value>
      <webElementGuid>46ff0ccc-ca52-4563-8bf2-a9dce4dc799b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[18]</value>
      <webElementGuid>7ccb5a34-341f-4388-8502-b359708cb735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'checkbox8']</value>
      <webElementGuid>44664fdf-4aa1-4d2d-867e-d9de2bf3334d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
