<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Radio8_radio9</name>
   <tag></tag>
   <elementGuidId>6529183d-7eb4-4613-a786-4144d95ba870</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#radio9</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio9']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>32222f4a-7052-4e87-beaa-45af6bb20790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>74ffbb99-b19f-4349-9518-187f5ad673d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio9</value>
      <webElementGuid>347db059-e56b-4946-8770-8b759501afba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Radio9</value>
      <webElementGuid>15a5f02b-c2fb-4ab3-8567-11db7c1495e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio9&quot;)</value>
      <webElementGuid>eb857cc7-0065-4519-8dd5-2c2e440d7771</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio9']</value>
      <webElementGuid>fe68c98f-3e91-41ba-b0ec-a63acb978640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[29]</value>
      <webElementGuid>3648e082-ef2b-4653-83b4-35d4173a9bec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'radio9']</value>
      <webElementGuid>10d21169-5db6-4d88-b84a-dc6630e97058</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
