<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text40_text40</name>
   <tag></tag>
   <elementGuidId>1fed8d76-ebda-46dc-b414-5984f0107f3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text40</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text40']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>65846cbc-8fa0-48a4-a370-6c67ed1e36fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>de6a5017-7a90-4944-9387-92ac8b346827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text40</value>
      <webElementGuid>0ec8477b-f748-48bc-8bf4-ce5ce2377a0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text40&quot;)</value>
      <webElementGuid>2309145e-26cd-4cc4-bac6-6ae741ded7ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text40']</value>
      <webElementGuid>b35efb0c-bb11-4c7f-a69a-b6925be2d4fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[40]</value>
      <webElementGuid>f1b1112b-993a-4e78-807a-222f55e74a34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text40']</value>
      <webElementGuid>6fb4b081-516c-4d44-93b8-de5af055bf84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
