<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text7_text7</name>
   <tag></tag>
   <elementGuidId>82b22b46-d7a0-4690-bafa-a9974fc1a9bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text7']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ec633a69-b49a-41b1-a7a0-e68d39465c48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8d25f71e-c2e7-4a5a-9959-eac491c5e0cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text7</value>
      <webElementGuid>cf9a6001-f2fa-4187-aebc-c84b40b9a2d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text7&quot;)</value>
      <webElementGuid>5b80488f-7a24-4ee7-8e0d-ba05c1c76f93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text7']</value>
      <webElementGuid>d587682b-1f6a-45c8-aff8-17cfaed9fa57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[7]</value>
      <webElementGuid>a9935615-8ba7-4fe8-ae21-38d3a61c3d2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text7']</value>
      <webElementGuid>d40f6c7f-57ef-47e5-bc96-a562627deccd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
