<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text11_text11</name>
   <tag></tag>
   <elementGuidId>d2cd1cf6-591c-4b26-8b39-dce9acfa7f87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text11</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text11']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dbeb7826-8862-4fde-9771-0a750d01db86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c61c084e-913a-4884-83ab-a0269ed5e0e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text11</value>
      <webElementGuid>bf6ca7a0-4066-4f00-bb84-02a8b0bb920b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text11&quot;)</value>
      <webElementGuid>1c2b93fe-4b3a-4f36-b3d0-aa4d15315a68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text11']</value>
      <webElementGuid>67d02f09-84ce-4040-bcf3-d066873e8887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[11]</value>
      <webElementGuid>1e9088ff-f8a4-456a-bf5c-d96edc40451d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text11']</value>
      <webElementGuid>e94ba5d6-941f-4551-867d-1446ae74052e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
