<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text2_text2</name>
   <tag></tag>
   <elementGuidId>33761ebd-94e6-4ccf-8aac-4b4ebf8d73c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>72e30d3a-59dc-4ef9-b643-b1e7ae64344a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>febe4978-c154-429b-939d-e62fe2df5884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text2</value>
      <webElementGuid>a5d8c6c6-154d-4439-9561-149d3cd61723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text2&quot;)</value>
      <webElementGuid>191b8272-0f70-4a7c-aba2-500e5f6a2a8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text2']</value>
      <webElementGuid>586e89f6-d695-4c8e-9b48-319312e6a08b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>2b42bee5-3d95-4c89-8c05-902a7161d529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text2']</value>
      <webElementGuid>75f85d6f-9b2c-47c8-a3f5-569dea060178</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
