<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text6_text6</name>
   <tag></tag>
   <elementGuidId>0d56aed4-9b25-40be-82cc-b7453ee409f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4dfe0f65-e75b-45a0-a63a-ce235074a670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>30ce0ae9-b116-425f-b81c-0b7285e85f5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text6</value>
      <webElementGuid>2f658b03-4b7e-4092-944d-70e2a8c5d8c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text6&quot;)</value>
      <webElementGuid>25dacdd3-3f7a-4672-aac8-2e7c13f17f89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text6']</value>
      <webElementGuid>cd74aa21-7b43-4e07-b95a-23e8eaa9cfd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[6]</value>
      <webElementGuid>877c9e7d-9e92-44bb-9d34-c24e93cf271a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text6']</value>
      <webElementGuid>1ddb3edf-5186-4173-a839-88ed1413f8cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
