<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text26_text26</name>
   <tag></tag>
   <elementGuidId>aca59acb-62d4-4450-bfda-a59070a1d23e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text26</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text26']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>94e9dde4-1a24-4fd6-bc78-c3a8d244699d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>61654737-1e4c-428e-af71-8658bcf690be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text26</value>
      <webElementGuid>663b78db-e932-4f37-8470-e5c3714d39fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text26&quot;)</value>
      <webElementGuid>7b2f08a2-e4d4-4084-9b90-9536c1ca4c94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text26']</value>
      <webElementGuid>345d536c-096a-446b-89a0-52f81ba75f21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[26]</value>
      <webElementGuid>1e9976ef-7bf3-4bf0-a1c9-437ead119eaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text26']</value>
      <webElementGuid>88bec3fe-94e1-42cb-98d9-23e0556cbc4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
