<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text34_text34</name>
   <tag></tag>
   <elementGuidId>a577ae0e-a912-4c27-8d7b-272ba69b6b31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text34</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text34']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0334ae42-ddc4-4b5c-9c81-a380ad717c45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>88640ef5-4498-4f2f-a90f-67428914988d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text34</value>
      <webElementGuid>df6c6d33-3296-455a-b42d-0ec609136bce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text34&quot;)</value>
      <webElementGuid>9ef120c5-327b-44d5-803e-9572df4f422b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text34']</value>
      <webElementGuid>55b4bcf0-ca20-4bda-8e40-b88e37a361bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[34]</value>
      <webElementGuid>b3f4e299-536f-4e79-8fc0-893d5526a6df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text34']</value>
      <webElementGuid>bb3e69bb-5c6e-4b59-9c6a-35f793be10e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
