<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text16_text16</name>
   <tag></tag>
   <elementGuidId>3176a2ce-7f73-4cd6-baff-3ab7e8dabf69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text16</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text16']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ff4efaef-e065-4a54-b985-5a5934811b47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4958c292-fff4-4725-96b4-15c7b0860bf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text16</value>
      <webElementGuid>15309590-b768-4db7-87a8-07b15239b466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text16&quot;)</value>
      <webElementGuid>db562002-19c9-4b43-94a3-1493551a1682</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text16']</value>
      <webElementGuid>e1a9c660-828b-4855-9ff2-bf2703835f22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[16]</value>
      <webElementGuid>067e07fc-6cfd-4426-9ae8-6ab432df62ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text16']</value>
      <webElementGuid>3e617c18-8930-4578-a375-1ed5b7fca6cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
