<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text3_text3</name>
   <tag></tag>
   <elementGuidId>66ef31c9-4131-4e46-bcea-6669b7a5170b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>875974fb-edd1-414a-80c2-f25682078d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6649a67c-c455-46e6-b339-ae66eb9d12a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text3</value>
      <webElementGuid>63dd6271-e809-46fd-8f70-90de35b2054a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text3&quot;)</value>
      <webElementGuid>5f6bc554-67dd-4f19-a229-31ab8b7cd6bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text3']</value>
      <webElementGuid>2e195140-e88d-455d-b5dc-f66f2fb0a503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>878b993c-a046-41d4-96ac-a414f14d9696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text3']</value>
      <webElementGuid>e23d9504-27fc-4e66-8089-6df65b628f76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
